services:
  app:
    image: registry.redyd.dev/redyd_dot_dev:latest
    container_name: redyd_dot_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - POCKETBASE_URL=http://redyd_pocketbase:8090
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - GEMINI_AI_MODEL=${GEMINI_AI_MODEL}
    networks:
      - proxy

networks:
  proxy:
    external: true