services:
  app:
    image: registry.redyd.dev/redyd_dot_dev:latest
    container_name: redyd_dot_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=redlab
    networks:
      - proxy

networks:
  proxy:
    external: true