name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: redyd-git/.github/.github/workflows/deploy.yml@main
    with:
      image_name: redyd_dot_dev
      compose_path: /opt/redyd_dot_dev
    secrets: inherit